export interface SeoPageContent {
  metaTitle: string;
  metaDescription: string;
  focusKeyword: string;
  contentHtml: string;
}

const company = "Teens Software Solutions";
const location = "Madhapur, Hyderabad";
const process = `
<h2>Our Process</h2>
<ol>
  <li><strong>Discovery and requirement analysis:</strong> We understand your goals, users and requirements before work begins.</li>
  <li><strong>Strategy and design:</strong> We create a clear plan, wireframes and prototypes for feedback.</li>
  <li><strong>Development and execution:</strong> Our Hyderabad-based team builds the solution with modern, scalable technologies.</li>
  <li><strong>Testing and optimization:</strong> We test functionality, performance and security, then refine the result.</li>
  <li><strong>Launch and ongoing support:</strong> We deploy, monitor and support your solution after release.</li>
</ol>
<h2>Why Choose Teens Software Solutions in Hyderabad?</h2>
<ul>
  <li>Strategic thinking aligned with your business goals.</li>
  <li>A dedicated Virtual CIO for personalized guidance.</li>
  <li>Transparent, results-driven delivery and reporting.</li>
  <li>Recognition including the Pride of Hyderabad Award 2025.</li>
</ul>`;

function serviceContent(service: string, intro: string, included: string, faqs: string[]): string {
  return `<p>${intro}</p><h2>What's Included in Our ${service}</h2><p>${included}</p>${process}<h2>Frequently Asked Questions</h2>${faqs.map((faq) => `<h3>${faq.split("|")[0]}</h3><p>${faq.split("|").slice(1).join("|")}</p>`).join("")}<p><strong>Ready to get started?</strong> Contact ${company}, ${location}, for a free consultation.</p>`;
}

const pages: Record<string, SeoPageContent> = {
  "/about": {
    metaTitle: "About Teens Software Solutions | IT Company in Hyderabad",
    metaDescription: "Learn about Teens Software Solutions, a Madhapur, Hyderabad-based IT company delivering software, web and digital marketing services. Meet our team and mission.",
    focusKeyword: "it company hyderabad",
    contentHtml: `<p>${company} is an IT company headquartered in ${location}, delivering software development, web design, digital marketing and IT support services to businesses across Hyderabad and beyond.</p><h2>Our Mission, Vision and Values</h2><p>Our mission is to be your trusted partner in navigating the digital landscape. We combine strategic thinking, innovation, collaboration, transparency and results-driven delivery, with a dedicated Virtual CIO for every client.</p><h2>Why Businesses in Hyderabad Choose Us</h2><p>We pair experienced delivery with personalized technology guidance and were recognized with the Pride of Hyderabad Award 2025.</p><h2>Frequently Asked Questions</h2><h3>What does Teens Software Solutions do?</h3><p>We offer software and web development, digital marketing and IT support services.</p><h3>Where is Teens Software Solutions located?</h3><p>We are headquartered in Madhapur, Hyderabad, and serve clients in India and internationally.</p><h3>Does every client receive a dedicated point of contact?</h3><p>Yes. Every client is assigned a dedicated Virtual CIO for ongoing strategic guidance.</p><p>Contact ${company}, ${location}, for a free consultation.</p>`,
  },
  "/branding-services": { metaTitle: "Branding Services in Hyderabad | Teens Software Solutions", metaDescription: "Build a powerful brand identity with Teens Software Solutions' branding services in Hyderabad - logo design, brand strategy and visual identity.", focusKeyword: "branding services hyderabad", contentHtml: serviceContent("Branding Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering brand strategy, logo design and visual identity development.`, "From logo design and brand guidelines to messaging and visual identity systems, we build recognizable brands that stay consistent across websites, marketing materials and social channels.", ["What does a branding company in Hyderabad do?|We define your visual identity, messaging and brand guidelines so your business looks consistent everywhere.", "How much do branding services cost in Hyderabad?|Cost depends on scope, from logo-only work to a complete brand identity system. Contact us for a custom quote.", "Why choose Teens Software Solutions for branding?|We connect design execution with your wider business goals and provide dedicated strategic guidance."]) },
  "/web-design-development-services": { metaTitle: "Web Design & Development Company in Hyderabad | Teens IT", metaDescription: "Custom, responsive web design and development services in Hyderabad. Teens Software Solutions builds fast, SEO-friendly websites for growing businesses.", focusKeyword: "software development company in hyderabad", contentHtml: serviceContent("Web Design and Development Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering custom, responsive website design and development for business websites and complex web applications.`, "We design and build responsive websites and web applications optimized for speed, security, conversions and search visibility.", ["What does a web design and development company in Hyderabad do?|We plan, design, build and maintain websites and web applications tailored to your goals.", "How much does website development cost in Hyderabad?|Pricing depends on complexity and features. Share your requirements for a custom quote.", "Why choose Teens Software Solutions?|Our design, development and SEO expertise helps your website rank and convert."]) },
  "/e-commerce-development": { metaTitle: "E-commerce Development Company in Hyderabad | Teens IT", metaDescription: "End-to-end e-commerce development services in Hyderabad - custom online stores, payment integration and scalable platforms.", focusKeyword: "ecommerce development company hyderabad", contentHtml: serviceContent("E-commerce Development Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering end-to-end e-commerce website development with secure payments and scalable platforms.`, "We build secure online stores with payment gateways, inventory management and mobile-optimized checkout, tailored to your catalogue and growth plans.", ["What does an e-commerce development company in Hyderabad do?|We design, build and maintain online stores with payments, inventory and checkout integrations.", "How much does e-commerce website development cost in Hyderabad?|Cost varies by platform, catalogue size and integrations. Get in touch for a custom quote.", "Why choose Teens Software Solutions?|We optimize stores for conversions and search visibility, with support after launch."]) },
  "/mobile-app-development-services": { metaTitle: "Mobile App Development Company in Hyderabad | Teens IT", metaDescription: "Android, iOS and cross-platform mobile app development services in Hyderabad. Teens Software Solutions builds scalable apps for startups and enterprises.", focusKeyword: "software company hyderabad", contentHtml: serviceContent("Mobile App Development Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering Android, iOS and cross-platform mobile app development from concept through launch.`, "We handle UX design, native or cross-platform development, testing and App Store and Play Store deployment end to end.", ["What does a mobile app development company in Hyderabad do?|We design, build, test and launch Android, iOS and cross-platform apps.", "How much does mobile app development cost in Hyderabad?|Cost depends on platform, features and complexity. Contact us for a tailored estimate.", "Why choose Teens Software Solutions?|We manage the complete app lifecycle with a dedicated Virtual CIO guiding the roadmap."]) },
  "/marketing-other-related-services": { metaTitle: "Marketing Services in Hyderabad | Teens Software Solutions", metaDescription: "Explore integrated marketing services in Hyderabad - branding, campaigns and growth marketing solutions from Teens Software Solutions.", focusKeyword: "marketing services hyderabad", contentHtml: serviceContent("Marketing Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering integrated marketing across branding, campaigns and growth marketing.`, "We support campaign strategy and creative execution alongside SEO, PPC and social media services.", ["What marketing services do you offer in Hyderabad?|We offer branding, campaign strategy and growth marketing alongside core digital marketing services.", "How much do marketing services cost in Hyderabad?|Cost depends on scope. Contact us for a custom quote."]) },
  "/project-management": { metaTitle: "IT Project Management Services in Hyderabad | Teens IT", metaDescription: "Reliable IT project management services in Hyderabad ensuring on-time, on-budget delivery. Partner with Teens Software Solutions for structured execution.", focusKeyword: "it project management services hyderabad", contentHtml: serviceContent("IT Project Management Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering structured IT project management for on-time, on-budget delivery.`, "We manage planning, resourcing, risk and delivery while keeping stakeholders informed with transparent reporting.", ["What does an IT project management service do?|We coordinate IT and software projects from kickoff to delivery, managing timelines, budgets and risks.", "Why choose Teens Software Solutions?|Our transparent, results-driven approach keeps projects on track and stakeholders informed."]) },
  "/software-testing": { metaTitle: "Software Testing Company in Hyderabad | Teens IT Solutions", metaDescription: "Comprehensive software testing services in Hyderabad - manual, automation and performance testing for bug-free, reliable software delivery.", focusKeyword: "it software companies in hyderabad", contentHtml: serviceContent("Software Testing Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering manual, automation and performance testing for reliable software delivery.`, "We cover functional, regression, automation and performance testing across web and mobile applications.", ["What does a software testing company do?|We test functionality, performance and security using manual and automated methods.", "Why choose Teens Software Solutions for testing?|Our QA team catches issues early, reducing cost and rework."]) },
  "/software-quality-assurance": { metaTitle: "Software QA Services in Hyderabad | Teens Software Solutions", metaDescription: "Ensure flawless software with Teens Software Solutions' QA services in Hyderabad - quality frameworks, audits and continuous testing support.", focusKeyword: "software quality assurance company hyderabad", contentHtml: serviceContent("Quality Assurance Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering QA frameworks, process audits and continuous testing support.`, "We build QA processes around your development cycle so quality issues are caught before production.", ["What does a software QA company do?|We build and run process audits, continuous testing and release checks.", "How is QA different from software testing?|Testing finds defects in a build; QA builds processes that help prevent defects. We offer both."]) },
  "/search-engine-optimization": { metaTitle: "SEO Company in Hyderabad | Teens Software Solutions", metaDescription: "Top-rated SEO services in Hyderabad - keyword research, on-page and off-page optimization to boost rankings. Get a free SEO audit today.", focusKeyword: "seo company hyderabad", contentHtml: serviceContent("SEO Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering keyword research, on-page, off-page and technical SEO.`, "We combine keyword research, technical SEO and content strategy to build sustainable organic visibility and qualified traffic.", ["What does an SEO company in Hyderabad do?|We research keywords, optimize content and technical structure, and build authority.", "How long does SEO take to show results?|Most businesses see measurable movement in 3-6 months; SEO is a long-term investment.", "Why choose Teens Software Solutions?|We combine advanced SEO strategies with transparent reporting."]) },
  "/social-media-optimization": { metaTitle: "Social Media Optimization Services Hyderabad | Teens IT", metaDescription: "Grow your brand presence with expert social media optimization services in Hyderabad from Teens Software Solutions.", focusKeyword: "social media optimization company hyderabad", contentHtml: serviceContent("Social Media Optimization Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering profile optimization and content strategy for stronger social discoverability.`, "We optimize profiles, create shareable content and position your brand across social platforms.", ["What does social media optimization involve?|SMO optimizes profiles and content strategy for visibility, engagement and shareability.", "How is SMO different from social media management?|SMO focuses on optimization; management covers ongoing posting and community engagement."]) },
  "/social-media-management": { metaTitle: "Social Media Management Company in Hyderabad | Teens IT", metaDescription: "End-to-end social media management services in Hyderabad - content, scheduling and analytics to grow engagement.", focusKeyword: "social media management company hyderabad", contentHtml: serviceContent("Social Media Management Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering end-to-end social content, scheduling and analytics management.`, "We manage content creation, scheduling, community engagement and analytics reporting so your presence stays active and on-brand.", ["What does a social media management company do?|We manage content calendars, posting, engagement and analytics across platforms.", "How much does social media management cost?|Pricing depends on platforms and content volume. Contact us for a custom quote."]) },
  "/pay-per-click": { metaTitle: "PPC Advertising Company in Hyderabad | Teens Software Solutions", metaDescription: "Drive measurable results with PPC advertising services in Hyderabad - Google Ads, targeted campaigns and ROI-focused management.", focusKeyword: "ppc advertising company hyderabad", contentHtml: serviceContent("PPC Advertising Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering targeted Google Ads and paid social campaigns.`, "We plan, launch and manage search and social campaigns, continuously optimizing return on ad spend.", ["What does a PPC advertising company do?|We manage Google and social ad campaigns to drive traffic and conversions.", "How much budget do I need for PPC?|Budgets vary by industry and competition; we recommend a starting budget during consultation."]) },
  "/content-writing-services": { metaTitle: "Content Writing Services in Hyderabad | Teens IT Solutions", metaDescription: "SEO-optimized content writing services in Hyderabad - website copy, blogs and marketing content crafted by Teens Software Solutions.", focusKeyword: "content writing services hyderabad", contentHtml: serviceContent("Content Writing Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering SEO-optimized website copy, blog content and marketing content.`, "Our writers create natural, search-friendly content for websites, blogs and marketing campaigns.", ["What does a content writing service offer?|We write SEO-optimized website copy, blog posts and marketing content tailored to your audience.", "Do you write blogs and websites?|Yes. We write ongoing blog content and core website pages for search and readability."]) },
  "/conversion-rate-optimization": { metaTitle: "Conversion Rate Optimization Services Hyderabad | Teens IT", metaDescription: "Improve website conversions with data-driven CRO services in Hyderabad - A/B testing, UX audits and funnel optimization.", focusKeyword: "conversion rate optimization company hyderabad", contentHtml: serviceContent("Conversion Rate Optimization Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering data-driven A/B testing and UX audits.`, "We audit user journeys, test changes and optimize funnels so more existing traffic converts.", ["What does a CRO company do?|We analyze user journeys and test changes to increase leads and customers.", "How is CRO different from SEO?|SEO brings visitors; CRO increases the percentage who take action. Most businesses need both."]) },
  "/online-reputation-management": { metaTitle: "Online Reputation Management Company Hyderabad | Teens IT", metaDescription: "Protect and build your brand's online reputation with Teens Software Solutions' ORM services in Hyderabad.", focusKeyword: "online reputation management company hyderabad", contentHtml: serviceContent("Online Reputation Management Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering monitoring, review management and response strategy.`, "We monitor mentions and reviews, respond strategically and build positive content that strengthens your online presence.", ["What does an online reputation management company do?|We monitor mentions, manage reviews and responses, and strengthen your reputation.", "Why does ORM matter for a Hyderabad business?|Customers check reviews and search results before choosing a provider, so reputation directly affects new business."]) },
  "/web-traffic-management": { metaTitle: "Web Traffic Management Services in Hyderabad | Teens IT", metaDescription: "Increase qualified website traffic with Teens Software Solutions' web traffic management services in Hyderabad.", focusKeyword: "web traffic management company hyderabad", contentHtml: serviceContent("Web Traffic Management Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering traffic analysis and channel optimization focused on qualified visitors.`, "We analyze traffic sources and quality, then optimize organic, paid and referral channels for relevant visits.", ["What does web traffic management involve?|We analyze traffic sources and optimize organic, paid and referral channels."]) },
  "/cyber-security-services": { metaTitle: "Cyber Security Services Company in Hyderabad | Teens IT", metaDescription: "Protect your business with Teens Software Solutions' cyber security services in Hyderabad - threat detection, VAPT and managed security.", focusKeyword: "cyber security company hyderabad", contentHtml: serviceContent("Cyber Security Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering threat detection, VAPT and managed security services.`, "We assess vulnerabilities, monitor threats and provide managed security support to protect systems, data and customer trust.", ["What does a cyber security company do?|We assess, monitor and protect systems through VAPT, threat monitoring and managed security.", "Does every business need cyber security?|Yes. Any business storing customer or financial data can be targeted, and proactive security costs less than recovery."]) },
  "/ai-machine-learning-services": { metaTitle: "AI & Machine Learning Company in Hyderabad | Teens IT", metaDescription: "Build intelligent solutions with Teens Software Solutions' AI and machine learning services in Hyderabad - custom models and automation.", focusKeyword: "ai machine learning company hyderabad", contentHtml: serviceContent("AI and Machine Learning Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering custom AI models, automation and data-driven applications.`, "We build machine learning models and automation workflows tailored to your business processes and available data.", ["What does an AI and machine learning company offer?|We build custom models, automation and data-driven applications.", "Do I need a lot of data to start with AI?|Not necessarily. We assess your existing data and recommend a realistic starting point."]) },
  "/oracle-pl-sql-services": { metaTitle: "Oracle & PL/SQL Services Company in Hyderabad | Teens IT", metaDescription: "Expert Oracle database and PL/SQL development services in Hyderabad - development, migration and ongoing support.", focusKeyword: "oracle pl sql services hyderabad", contentHtml: serviceContent("Oracle and PL/SQL Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering Oracle database development, migration and PL/SQL support.`, "We support database development, migration, performance tuning and ongoing PL/SQL work for Oracle systems.", ["What does an Oracle and PL/SQL services company do?|We provide Oracle development, migration, tuning and PL/SQL programming support."]) },
  "/sap-support-greenfield-implementation-services": { metaTitle: "SAP Support & Implementation Services Hyderabad | Teens IT", metaDescription: "SAP support and greenfield implementation services in Hyderabad - Teens Software Solutions helps enterprises deploy and manage SAP efficiently.", focusKeyword: "sap support services hyderabad", contentHtml: serviceContent("SAP Support and Greenfield Implementation Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering SAP support and new greenfield implementation services.`, "We support ongoing SAP maintenance and fresh implementations with minimal disruption to enterprise operations.", ["What is a greenfield SAP implementation?|It is a fresh SAP implementation built from the ground up rather than an upgrade or migration."]) },
  "/it-recruitment": { metaTitle: "IT Staffing & Recruitment Company in Hyderabad | Teens IT", metaDescription: "Find the right IT talent fast with Teens Software Solutions' IT staffing services in Hyderabad - permanent, contract and remote recruitment.", focusKeyword: "it staffing company hyderabad", contentHtml: serviceContent("IT Staffing Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering temporary, permanent, remote and offshore IT recruitment.`, "We source and place technical talent for temporary, permanent, remote and offshore roles, with a free consultation.", ["What does an IT staffing company do?|We find and place IT talent for permanent, contract, remote and offshore roles.", "Do you offer a free consultation?|Yes. We offer a complimentary, no-obligation consultation."]) },
  "/telemarketing-services": { metaTitle: "Telemarketing Services Company in Hyderabad | Teens IT", metaDescription: "Boost sales with professional telemarketing services in Hyderabad from Teens Software Solutions - lead generation and customer outreach.", focusKeyword: "telemarketing services hyderabad", contentHtml: serviceContent("Telemarketing Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering lead generation and customer outreach.`, "We run outbound campaigns that engage prospects and communicate product or service benefits to support sales.", ["What does a telemarketing service offer?|We run outbound calling campaigns for lead generation and customer outreach."]) },
  "/it-outsourcing-services": { metaTitle: "IT Outsourcing Company in Hyderabad | Teens Software Solutions", metaDescription: "Cut costs and scale faster with Teens Software Solutions' IT outsourcing services in Hyderabad - managed IT, development and support teams.", focusKeyword: "it outsourcing company hyderabad", contentHtml: serviceContent("IT Outsourcing Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering managed IT, development and support teams.`, "We provide managed teams so businesses can scale without the overhead of building an in-house department.", ["What does an IT outsourcing company do?|We provide managed IT, development and support teams that can scale with your needs.", "How is IT outsourcing different from IT staffing?|Staffing places individual talent; outsourcing hands over a function or project to a managed team."]) },
  "/help-desk-services": { metaTitle: "Help Desk Support Services Company in Hyderabad | Teens IT", metaDescription: "Reliable IT help desk services in Hyderabad - 24/7 technical support, ticketing and issue resolution.", focusKeyword: "help desk services hyderabad", contentHtml: serviceContent("Help Desk Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering 24/7 technical support, ticketing and issue resolution.`, "We provide round-the-clock support with structured ticketing and fast resolution for employees or customers.", ["What does a help desk service provide?|We provide 24/7 technical support, ticket management and issue resolution."]) },
  "/monitoring-services": { metaTitle: "IT Monitoring Services Company in Hyderabad | Teens IT", metaDescription: "Keep systems running smoothly with Teens Software Solutions' IT monitoring services in Hyderabad - infrastructure, network and performance monitoring.", focusKeyword: "it monitoring services hyderabad", contentHtml: serviceContent("IT Monitoring Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering infrastructure, network and application performance monitoring.`, "We provide systematic oversight to catch issues before they affect uptime, security or efficiency.", ["What does IT monitoring cover?|It covers infrastructure, network and application performance to maintain uptime, security and efficiency."]) },
  "/client-support-services": { metaTitle: "Client Support Services Company in Hyderabad | Teens IT", metaDescription: "Dedicated client support services in Hyderabad from Teens Software Solutions - responsive, reliable customer success support.", focusKeyword: "client support services hyderabad", contentHtml: serviceContent("Client Support Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering responsive, dedicated client support focused on customer success.`, "We resolve issues quickly and build long-term client relationships through dedicated support.", ["What does a client support service offer?|We provide responsive support that helps customers or clients succeed with your product or service."]) },
  "/inbound-outbound-support": { metaTitle: "Inbound & Outbound Support Services Hyderabad | Teens IT", metaDescription: "Professional inbound and outbound call support services in Hyderabad from Teens Software Solutions - customer service and outreach.", focusKeyword: "inbound outbound support services hyderabad", contentHtml: serviceContent("Inbound and Outbound Support Services", `${company} is a Hyderabad-based IT company headquartered in ${location}, offering call support for inbound customer service and outbound outreach.`, "We handle inbound customer calls and outbound campaigns through one coordinated customer communication team.", ["What is the difference between inbound and outbound support?|Inbound support handles incoming queries; outbound support is proactive outreach such as sales or follow-up calls. We offer both."]) },
  "/blog": { metaTitle: "Blog | Software, IT & Digital Marketing Insights - Teens IT", metaDescription: "Explore the latest insights on software development, IT trends and digital marketing from Teens Software Solutions, Hyderabad.", focusKeyword: "software companies in hyderabad", contentHtml: `<p>The ${company} blog shares practical insights on software development, IT trends and digital marketing from our Hyderabad-based team.</p><h2>What You'll Find Here</h2><p>Explore guides on choosing a software development company in Hyderabad, SEO, mobile apps and IT trends before you request a quote.</p><p>Contact ${company}, ${location}, for a free consultation.</p>` },
  "/top-software-companies-in-hyderabad": { metaTitle: "Top Software Companies in Hyderabad (2026 List) | Teens IT", metaDescription: "A curated list of the top software companies in Hyderabad in 2026, what sets them apart, and how to choose the right IT partner for your project.", focusKeyword: "top software companies in hyderabad", contentHtml: `<p>Hyderabad is one of India's leading IT hubs, home to global majors and specialized software companies serving startups and enterprises.</p><h2>What Makes a Software Company Top in Hyderabad?</h2><p>Evaluate delivery track record, technology expertise, client reviews and whether the company assigns a dedicated point of contact such as a Virtual CIO.</p><h2>How to Choose the Right Software Partner</h2><p>Shortlist companies whose portfolios match your web, mobile, e-commerce or enterprise project, then compare communication, transparency and post-launch support.</p><h2>Why Teens Software Solutions</h2><p>${company}, headquartered in ${location}, offers software development, digital marketing and IT support under one roof, with a dedicated Virtual CIO for every client.</p><h2>Frequently Asked Questions</h2><h3>What should I look for in a top software company in Hyderabad?</h3><p>Look for proven delivery, relevant expertise, transparent communication and a dedicated point of contact.</p><h3>Is Teens Software Solutions a good fit for enterprise projects?</h3><p>Yes. We support startups and enterprises across software development, IT support and digital marketing.</p><p>Contact ${company}, ${location}, for a free consultation.</p>` },
  "/list-of-software-companies-in-hyderabad": { metaTitle: "List of Software Companies in Hyderabad | Teens IT Solutions", metaDescription: "Browse a detailed list of software companies in Hyderabad across IT services, product engineering and startups, with what each specializes in.", focusKeyword: "list of software companies in hyderabad", contentHtml: `<p>Hyderabad's software ecosystem spans IT services firms, product engineering studios and niche technology specialists.</p><h2>Types of Software Companies in Hyderabad</h2><p>IT services companies provide development, staffing and support; product companies build their own software; specialized agencies focus on mobile, e-commerce or AI and ML.</p><h2>What Teens Software Solutions Offers</h2><p>We cover web and mobile development, e-commerce, software testing and QA, digital marketing and IT support from our ${location} office.</p><h2>Frequently Asked Questions</h2><h3>How is Teens Software Solutions different from a typical IT services company?</h3><p>We combine software development, digital marketing and IT support under one team, reducing the need to coordinate multiple vendors.</p><p>Contact ${company}, ${location}, for a free consultation.</p>` },
  "/startup-software-companies-in-hyderabad": { metaTitle: "Startup Software Companies in Hyderabad | Teens IT Solutions", metaDescription: "Discover emerging startup software companies in Hyderabad and how Teens Software Solutions supports startups with agile development.", focusKeyword: "startup software companies in hyderabad", contentHtml: `<p>Hyderabad's startup ecosystem needs software partners who move quickly, work within lean budgets and scale support as the business grows.</p><h2>What Startups Should Look for in a Tech Partner</h2><p>Prioritize flexibility, transparent pricing and a partner comfortable with agile, iterative development.</p><h2>How Teens Software Solutions Supports Startups</h2><p>We work with Hyderabad startups on MVP development, mobile apps and digital marketing, with a dedicated Virtual CIO adapting recommendations as the business evolves.</p><h2>Frequently Asked Questions</h2><h3>Does Teens Software Solutions work with early-stage startups?</h3><p>Yes. We support startups from MVP development through growth-stage digital marketing and IT support.</p><p>Contact ${company}, ${location}, for a free consultation.</p>` },
  "/contact": { metaTitle: "Contact Us | Teens Software Solutions, Madhapur, Hyderabad", metaDescription: "Get in touch with Teens Software Solutions in Madhapur, Hyderabad - call, email or visit us for IT, software and digital marketing services.", focusKeyword: "it company hyderabad", contentHtml: `<p>${company} is located in ${location}. Reach out for IT, software development or digital marketing services; our team responds to every enquiry.</p><h2>Get in Touch</h2><p>Unit No. 303 B, 3rd Floor, New Mark House, Plot No. 56, Patrika Nagar, Madhapur, Hyderabad - 500081.</p><p>Phone: +91-9032938676<br>Email: info@teensitsolutions.com<br>Open Monday-Saturday, 9 am-6 pm (closed Sunday).</p><h2>Frequently Asked Questions</h2><h3>Where is Teens Software Solutions located?</h3><p>We are located in Madhapur, Hyderabad - 500081.</p><h3>What are your business hours?</h3><p>We are open Monday to Saturday, 9 am to 6 pm, and closed on Sundays.</p><p>Contact ${company}, ${location}, for a free consultation.</p>` },
};

export function getSeoPageContent(route: string): SeoPageContent | null {
  return pages[route] ?? null;
}
